import type { MetadataRoute } from "next";
import routes from "@/lib/routes.json";
import { absoluteUrl } from "@/lib/site";

/**
 * The sitemap.
 *
 * Every URL comes from `routes.json`, generated by scripts/build-routes.mjs on
 * `prebuild`. Nothing here touches the filesystem or spawns a process, and that
 * is the whole point: an earlier version walked `src/app` and shelled out to
 * `git` from inside this function. It built cleanly, `next build` even reported
 * it as `○ Static`, and it still returned 500 on the deployed Worker — OpenNext
 * calls this at request time, where there is no filesystem and no git.
 *
 * So: no `node:*` imports in this file, ever. If the sitemap needs to know
 * something new, work it out in the build script and add it to the JSON.
 */
export const dynamic = "force-static";

/**
 * Relative weight within the site. Google treats `priority` as a hint at most,
 * but it costs nothing and states the intended shape: the landing page first,
 * then the docs people arrive for, then everything else.
 */
function priorityFor(route: string): number {
  if (route === "/") return 1;
  if (route === "/docs") return 0.9;
  if (route.startsWith("/docs/")) return 0.8;
  if (route === "/privacy") return 0.3;
  return 0.5;
}

function changeFrequency(route: string): "weekly" | "monthly" | "yearly" {
  if (route === "/" || route.startsWith("/docs")) return "weekly";
  if (route === "/privacy") return "yearly";
  return "monthly";
}

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map(({ route, lastModified }) => ({
    url: absoluteUrl(route),
    ...(lastModified ? { lastModified: new Date(lastModified) } : {}),
    changeFrequency: changeFrequency(route),
    priority: priorityFor(route),
  }));
}
